# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

parameters:
  - name: ImageName
    displayName: Docker Image name
    type: string
    default: 'devopsubuntu'
  - name: Tag
    displayName: Docker Tag to be used.
    type: string
    default: 'latest'
  - name: AppendMode
    displayName: Append Mode - tag or image.
    type: string
    default: 'image'
  - name: OSVersion
    displayName: Ubuntu OS Version to be used.
    type: string
    default: '18.04'
    values:
      - '16.04'
      - '18.04'
  - name: targets
    displayName: Build Targets - Comma separated list of Targets to build
    type: string
    default: 'base,python,docker,dotnet,nodejs'

trigger:
  - master
    
resources:
- repo: self

variables:
  DockerHubPrefix: $(DOCKER_HUB_USER)
  ImageName: ${{ parameters.ImageName }}
  Tag: ${{ parameters.Tag }}
  AppendMode: ${{ parameters.AppendMode }}
  OSVersion: ${{ parameters.OSVersion }}
  targets: ${{ parameters.targets }}
    
stages:
  - stage: Build
    displayName: Build image
    jobs:  
    - ${{ each target in parameters.targets }}:
      - job: build-${{ target }} 
        displayName: Build ${{ target }}
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - bash: |
              echo "Pipeline variables:"
              echo "DockerHubPrefix=$(DockerHubPrefix)"
              echo "ImageName=$(ImageName)"
              echo "Tag=$(Tag)"
              echo "AppendMode=$(AppendMode)"
              echo "OSVersion=$(OSVersion)"
              echo "targets=$(targets)"
              set
            displayName: 'Debug Variables'
      # - task: Docker@2
      #   displayName: Build image
      #   inputs:
      #     command: build
      #     dockerfile: '$(Build.SourcesDirectory)//Dockerfile'
      #     tags: |
      #       $(tag)