# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

parameters:
  - name: ImageName
    displayName: Docker Image Name
    type: string
    default: 'azure-devops-agent'
  - name: Tag
    displayName: Docker Tag
    type: string
    default: 'latest'
  - name: OSVersion
    displayName: Ubuntu OS Version to be used.
    type: string
    default: '18.04'
    values:
      - '16.04'
      - '18.04'
  # - name: targets
  #   displayName: Build Targets - Comma separated list of Targets to build
  #   type: jobList
  #   default: []
    #default: 'base,python,docker,dotnet,nodejs'

trigger:
  - master
    
resources:
- repo: self

variables:
  DockerHubPrefix: $(DOCKER_HUB_USER)
  ImageName: ${{ parameters.ImageName }}
  Tag: ${{ parameters.Tag }}
  OSVersion: ${{ parameters.OSVersion }}
  #targets: ${{ parameters.targets }}
    
jobs:
- template: job.yml
  parameters:
    jobs:
      - job: base

      - job: docker
        dependsOn: base

      - job: dotnet
        dependsOn: base

      - job: nodejs
        dependsOn: base

      - job: python
        dependsOn: base
    