# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

parameters:
  - name: ImageName
    displayName: Docker Image Name
    type: string
    default: 'azure-devops-agent'
  - name: Tag
    displayName: Docker Tag
    type: string
    default: 'latest'
  - name: OSVersion
    displayName: Ubuntu OS Version to be used.
    type: string
    default: '18.04'
    values:
      - '16.04'
      - '18.04'

trigger:
  - master
  - feature/*
    
resources:
- repo: self

jobs:
- template: job.yml
  parameters:
    jobs:
      - job: base

      - job: docker
        dependsOn: base

      - job: dotnet
        dependsOn: base

      - job: nodejs
        dependsOn: base

      - job: python
        dependsOn: base

    tag: ${{ parameters.Tag }}
    image: ${{ parameters.ImageName }}
    OSVersion: ${{ parameters.OSVersion }}

    